### ISSUE TITLE
Clicking dots for skills/attributes should fill in previous dots with javascript

### ISSUE THREAD

**Issue by sublimemarch** [deadcity/charsys#98]

**Comment by sublimemarch** [comment]
This.... is hard. Carly and I agreed that we're moving it to enhancements.

**Comment by carlydotwebsite** [comment]
This is still going to be rough but I have a vague idea of how to implement it:
- Use JS to wrap each of the radio buttons in a span and insert a FontAwesome fa-circle-o before it. Set the span to a fixed height/width w/ display:inline-block and overflow:hidden and push the radio button outside the visible area
- Find which one has the :checked flag and use .prevAll to remove fa-circle-o and replace it with .fa-circle (and also change the one that is checked to that)
- make the stuff I wrote in the previous bullet an onChange function and trigger it on pageload?
- set up click handlers for the dots so that they'll check the radio button directly after them
- ???????
- PROFIT

**Comment by sublimemarch** [comment]
Sounds like a good plan!

**Comment by carlydotwebsite** [comment]
Actually, now that I think about it, we can do the first step without javascript and just insert that stuff in the form template itself—it's a little obnoxious, but will probably reduce load time.
